Sp_Web_BanSach/MyPhamOnline/Areas/Admin/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyPhamOnline.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;
namespace MyPhamOnline.Areas.Admin.Controllers
{
    public class DonHangController : Controller
    {
        dbMyPhamOnlineDataContext db = new dbMyPhamOnlineDataContext();
        // GET: Admin/KhachHang
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 7;
            var lst = db.DONDATHANGs.ToList().OrderBy(n => n.MaDonHang).ToPagedList(iPageNum, iPageSize);
            return View(lst);
        }
    }
}

Sp_Web_BanSach/MyPhamOnline/Areas/Admin/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyPhamOnline.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace MyPhamOnline.Areas.Admin.Controllers
{
    public class KhachHangController : Controller
    {
        dbMyPhamOnlineDataContext db = new dbMyPhamOnlineDataContext();
        // GET: Admin/KhachHang
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 7;
            var lst = db.KHACHHANGs.ToList().OrderBy(n => n.MaKH).ToPagedList(iPageNum, iPageSize);
            return View(lst);
        }
    }
}

Sp_Web_BanSach/MyPhamOnline/Areas/Admin/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyPhamOnline.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;


namespace MyPhamOnline.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
        dbMyPhamOnlineDataContext db = new dbMyPhamOnlineDataContext();
        // GET: Admin/SanPham
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 7;
            var lst = db.SANPHAMs.ToList().OrderBy(n => n.MaSP).ToPagedList(iPageNum, iPageSize);
            return View(lst);
        }
        public ActionResult Create()
        {
            ViewBag.MaDS = new SelectList(db.DANHSACHSPs.ToList().OrderBy(n => n.TenDS), "MaDS", "TenDS");
            ViewBag.MaTH = new SelectList(db.THUONGHIEUs.ToList().OrderBy(n => n.TenTH), "MaTH", "TenTH");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(SANPHAM sanpham, FormCollection f, HttpPostedFileBase fFileUpload)
        {
            ViewBag.MaDS = new SelectList(db.DANHSACHSPs.ToList().OrderBy(n => n.TenDS), "MaDS", "TenDS");
            ViewBag.MaTH = new SelectList(db.THUONGHIEUs.ToList().OrderBy(n => n.TenTH), "MaTH", "TenTH");


            if (fFileUpload == null)
            {
                ViewBag.ThongBao = "Hãy chọn ảnh bìa.";
                ViewBag.TenSP = f["sTenSP"];
                ViewBag.MoTa = f["sMoTa"];
                ViewBag.SoLuong = int.Parse(f["iSoLuong"]);
                ViewBag.GiaBan = decimal.Parse(f["mGiaBan"]);
                ViewBag.MaDS = new SelectList(db.DANHSACHSPs.ToList().OrderBy(n => n.TenDS), "MaDS", "TenDS", int.Parse(f["MaDS"]));
                ViewBag.MaTH = new SelectList(db.THUONGHIEUs.ToList().OrderBy(n => n.TenTH), "MaTH", "TenTH", int.Parse(f["MaTH"]));
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                    {
                        fFileUpload.SaveAs(path);
                    }
                    sanpham.TenSP = f["sTenSp"];
                    sanpham.MoTa = f["sMoTa"].Replace("<p>", "").Replace("</p>", "\n");
                    sanpham.AnhBia = sFileName;
                    sanpham.NgayCapNhat = Convert.ToDateTime(f["dNgayCapNhat"]); 
                    sanpham.SoLuongBan = int.Parse(f["iSoLuong"]);
                    sanpham.GiaBan = decimal.Parse(f["mGiaBan"]); 
                    sanpham.MaDS = int.Parse(f["MaDS"]);
                    sanpham.MaTH = int.Parse(f["MaTH"]); 
                    db.SANPHAMs.InsertOnSubmit(sanpham); 
                    db.SubmitChanges();
                    return RedirectToAction("Index");
                }
                return View();
            }
        }
                public ActionResult DeTails(int id)
        {
            var sanpham = db.SANPHAMs.SingleOrDefault(n => n.MaSP == id);
            if (sanpham == null)
            {
                Response.StatusCode = 404;
            }
            return View(sanpham);
        }
        public ActionResult Delete(int id)
        {
            var sanpham = db.SANPHAMs.SingleOrDefault(n => n.MaSP == id);
            if (sanpham == null)
            {
                Response.StatusCode = 404;
            }
            return View(sanpham);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id, FormCollection f)
        {
            var sanpham = db.SANPHAMs.SingleOrDefault(n => n.MaSP == id);

            if (sanpham == null)
            {
                Response.StatusCode = 404; return null;
            }
            var ctdh = db.CHITIETDATHANGs.Where(ct => ct.MaSP == id); if (ctdh.Count() > 0)
            {
                ViewBag.ThongBao = "Sách này đang có trong bảng Chi tiết đặt hàng <br>" + " Nếu muốn xóa thì phải xóa hết mã sách này trong bảng Chi tiết đặt hàng";
                return View(sanpham);
            }

            var sanxuat = db.SANXUATs.Where(vs => vs.MaSP == id).ToList();
            if (sanxuat != null)
            {
                db.SANXUATs.DeleteAllOnSubmit(sanxuat);
                db.SubmitChanges();
            }
             return RedirectToAction("Index");
        }
        public ActionResult Edit()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var sanpham = db.SANPHAMs.SingleOrDefault(n => n.MaSP == id); if (sanpham == null)
            {
                Response.StatusCode = 404; return null;
            }
            ViewBag.MaDS = new SelectList(db.DANHSACHSPs.ToList().OrderBy(n => n.TenDS), "MaDS", "TenDS", sanpham.MaDS);
            ViewBag.MaTH = new SelectList(db.THUONGHIEUs.ToList().OrderBy(n => n.TenTH), "MaTH", "TenTH", sanpham.MaTH);
            return View(sanpham);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            var sanpham = db.SANPHAMs.SingleOrDefault(n => n.MaSP == int.Parse(f["iMaSP"])); ViewBag.MaCD = new SelectList(db.DANHSACHSPs.ToList().OrderBy(n => n.TenDS),
            "MaDS", "TenDS", sanpham.MaDS);
            ViewBag.MaTH = new SelectList(db.THUONGHIEUs.ToList().OrderBy(n => n.TenTH), "MaTH", "TenTH", sanpham.MaTH);

            if (ModelState.IsValid)
            {
                if (fFileUpload != null)
                {
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                    {
                        fFileUpload.SaveAs(path);
                    }
                    sanpham.AnhBia = sFileName;
                }
                sanpham.MoTa = f["sMoTa"].Replace("<p>", "").Replace("</p>", "\n");

                sanpham.NgayCapNhat = Convert.ToDateTime(f["dNgayCapNhat"]); sanpham.SoLuongBan = int.Parse(f["iSoLuong"]);
                sanpham.GiaBan = decimal.Parse(f["mGiaBan"]); sanpham.MaDS = int.Parse(f["MaDS"]); sanpham.MaTH = int.Parse(f["MaTH"]); db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return View(sanpham);
        }
    }
}

Sp_Web_BanSach/MyPhamOnline/Controllers/ThuongHieuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyPhamOnline.Models;

namespace MyPhamOnline.Controllers
{
    public class ThuongHieuController : Controller
    {
       dbMyPhamOnlineDataContext data = new dbMyPhamOnlineDataContext();
        // GET: ThuongHieu

        public ActionResult Index()
        {
            return View(from th in data.THUONGHIEUs select th);
        }
        public ActionResult Details()
        {
            int math = int.Parse(Request.QueryString["id"]);
            var result = data.THUONGHIEUs.Where(th => th.MaTH == math).SingleOrDefault();
            return View(result);
        }
        public THUONGHIEU GetTH(int id)
        {
            return (data.THUONGHIEUs.OrderBy(n => n.TenTH).Where(n => n.MaTH == id).SingleOrDefault());
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            //NHAXUATBAN nxb = data.NHAXUATBANs.Where(n => n.MaNXB == id).SingleOrDefault();
            //return View(nxb);
            return View(GetTH(id));
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit()
        {
            if (ModelState.IsValid)
            {
                var th = GetTH(int.Parse(Request.Form["MaTH"]));
                th.TenTH = Request.Form["TenTH"];
                th.TieuSu = Request.Form["TieuSu"];
                //UpdateModel(nxb);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Edit");
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(GetTH(id));
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection f)
        {
            var sach = GetTH(id);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //var ctdh = data.CHITIETDATHANGs.Where(ct => ct.MaSach == id).ToList();
            //if (ctdh != null)
            //{
            //    ViewBag.ThongBao = "Sách này đang có trong bảng Chi tiết đặt hàng!";
            //    return RedirectToAction("Delete");
            //}
            data.THUONGHIEUs.DeleteOnSubmit(sach);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FormCollection f)
        {
            if (ModelState.IsValid)
            {
                THUONGHIEU th = new THUONGHIEU();
                th.MaTH = int.Parse(Request.Form["MaTH"]);
                th.TenTH = Request.Form["TenTH"];
                th.TieuSu = Request.Form["TieuSu"];
                data.SubmitChanges();
                data.THUONGHIEUs.InsertOnSubmit(th);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Delete");
            }
        }
    }
}

Sp_Web_BanSach/MyPhamOnline/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial- scale=1">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css") @Scripts.Render("~/Scripts/js")

</head>
<body>


    <nav class="navbar navbar-static-top" style="background-color:darkkhaki;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navAdmin" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"style="background-color:darkkhaki;" href="@Url.Action("Index","Home")">Admin</a>
            </div>
            <div class="collapse navbar-collapse" id="navAdmin">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index","SanPham")">QUẢN LÝ SẢN PHẨM</a> </li>
                    <li><a href="@Url.Action("Index","DanhSachSP")">QUẢN LÝ DANH MỤC SẢN PHẨM</a> </li>
                    <li><a href="@Url.Action("Index","ThuongHieu")">QUẢN LÝ THƯƠNG HIỆU </a> </li>
                    <li><a href="@Url.Action("Index","KhachHang")">QUẢN LÝ KHÁCH HÀNG</a> </li>
                    <li>
                        <a href="@Url.Action("Index","DonHang")">QUẢN LÝ ĐƠN HÀNG</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    <footer class="container well">
        <div style="text-align:center;">
            <p>ADMIN</p>
        </div>
    </footer>
</body>
</html>

@using (Html.BeginForm("Search", "Search", FormMethod.Get, new { @class = "navbar- form navbar-right", @role = "search" }))
{
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Tìm kiếm" name="strSearch">
    </div>

    <button type="submit" class="btn btn-default">Tìm</button>
}

    <nav class="navbar navbar-static-top" style="background-color:darkkhaki;">
    <!--navbar-fixed-top-->
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <nav class="navbar navbar-static-top" style="background-color:darkkhaki;">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar1" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar navbar-static-top" style="background-color:darkkhaki;" href="#">Mỹ Phẩm Online</a>
            </nav>
        </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <!-- /.navbar-collapse -->
    </nav>
    <!-- /.container-->